apiVersion: v1
kind: Service
metadata:
  name: wso2mi-service
  namespace: ian
spec:
  type: NodePort
  selector:
    app: wso2mi
  ports:
    - name: http
      port: 8290
      targetPort: 8290
      nodePort: 30290
    - name: https
      port: 8253
      targetPort: 8253
      nodePort: 30253