---
key: "swagger-files-1.0.0"
name : "swagger-files"
displayName : "swagger-files"
description: "swagger-files"
version: "1.0.0"
serviceUrl: "https://{MI_HOST}:{MI_PORT}/default"
definitionType: "OAS3"
securityType: "BASIC"
mutualSSLEnabled: false